language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - DB_USER="root"
    - DB_PASS=""

services:
  - mysql

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mysql -e 'CREATE DATABASE silex_boilerplate;'
  - composer install

script: phpunit
